### ISSUE TITLE
Support Asset $BOMB

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/contracts#111]
We'd like to support yet another custom asset

**Symbol**: BOMB
**Block Explorer URL**:  https://bscscan.com/address/0x522348779dcb2911539e76a1042aa922f9c47ee3
**Chain**: BSC

- [ ] **ChainLink Supported**
- [x] **Requires Custom Oracle** 
- [x] **Requires Custom Liquidator**
- [ ] **ERC 4626 Support**
  - Link to ERC4626 ticket: https://github.com/Midas-Protocol/contracts/issues/117

### Tasks

- [ ] Implement deployment of TWAP pair for BOMB token on BSC
