### ISSUE TITLE
Support Asset $3EPS

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/contracts#112]
We'd like to support yet another custom asset

**Symbol**: 3EPS
**Block Explorer URL**:  https://bscscan.com/address/0xaF4dE8E872131AE328Ce21D909C74705d3Aaf452
**Chain**: BSC

- [ ] **ChainLink Supported**
- [x] **Requires Custom Oracle** 
- [x] **Requires Custom Liquidator**
- [x] **ERC 4626 Support**
  - Link to ERC4626 ticket: https://github.com/Midas-Protocol/contracts/issues/53

### Tasks

- [x] Implement custom oracle
- [x] Edit deployment script to set up and deploy oracle
- [ ] Implement custom liquidator
