### ISSUE TITLE
Support Asset $dai3EPS

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/contracts#113]
We'd like to support yet another custom asset

**Symbol**: dai3EPS
**Block Explorer URL**:  https://bscscan.com/address/0x0bc3a8239b0a63e945ea1bd6722ba747b9557e56
**Chain**: BSC

- [ ] **ChainLink Supported**
- [x] **Requires Custom Oracle** 
- [x] **Requires Custom Liquidator**
- [x] **ERC 4626 Support**
  - Link to ERC4626 ticket: https://github.com/Midas-Protocol/contracts/issues/53

### Tasks

- [x] Implement custom oracle
- [x] Edit deployment script to set up and deploy oracle
- [ ] Implement custom liquidator
