### ISSUE TITLE
Support Asset $ust3EPS

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/contracts#114]
We'd like to support yet another custom asset

**Symbol**: ust3EPS
**Block Explorer URL**:  https://bscscan.com/address/0x151F1611b2E304DEd36661f65506f9D7D172beba
**Chain**: BSC

- [ ] **ChainLink Supported**
- [x] **Requires Custom Oracle** 
- [x] **Requires Custom Liquidator**
- [x] **ERC 4626 Support**
  - Link to ERC4626 ticket: https://github.com/Midas-Protocol/contracts/issues/53

### Tasks

- [x] Implement custom oracle
- [x] Edit deployment script to set up and deploy oracle
- [ ] Implement custom liquidator
