### ISSUE TITLE
Support Asset $jBRL

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/contracts#115]
We'd like to support yet another custom asset

**Symbol**: jBRL
**Block Explorer URL**:  https://bscscan.com/address/0x0fd8170dc284cd558325029f6aec1538c7d99f49
**Chain**: BSC

- [x] **ChainLink Supported**
- [ ] **Requires Custom Oracle** 
- [x] **Requires Custom Liquidator**
- [ ] **ERC 4626 Support**
  - Link to ERC4626 ticket: N/A

### Tasks

- [ ] Edit deployment script to set up and deploy oracle
- [x] Implement custom liquidator

### Notes

Jarvis docs and addresses: https://learn.jarvis.network/protocol-overview/contracts/bnb-chain-v2
