### ISSUE TITLE
Support Asset $xBOMB

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/contracts#116]
We'd like to support yet another custom asset

**Symbol**: xBOMB
**Block Explorer URL**:  https://bscscan.com/address/0xaf16cb45b8149da403af41c63abfebfbcd16264b
**Chain**: BSC

- [ ] **ChainLink Supported**
- [x] **Requires Custom Oracle** 
- [x] **Requires Custom Liquidator**
- [x] **ERC 4626 Support**
  - Link to ERC4626 ticket: N/A

### Tasks

- [ ] Implement custom oracle
- [ ] Edit deployment script to set up and deploy oracle
- [x] Implement custom liquidator
