### ISSUE TITLE
Support Asset $BOMB-BTCB LP Token

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/contracts#149]
We'd like to support yet another custom asset

**Symbol**: BOMB-BTCB LP
**Block Explorer URL**:  https://bscscan.com/address/0x84392649eb0bC1c1532F2180E58Bae4E1dAbd8D6
**Chain**: BSC

- [ ] **ChainLink Supported**
- [x] **Requires Custom Oracle** 
- [x] **Requires Custom Liquidator**
- [x] **ERC 4626 Support**
  - Link to ERC4626 ticket: https://github.com/Midas-Protocol/contracts/issues/150

### Tasks

- [ ] Implement custom oracle
- [ ] Implement custom liquidator
- [ ] Edit deployment script to set up and deploy oracle and liquidator

### Notes

The oracle will be a classic LP token oracle, the underlying assets already have an oracle implemented (TWAP for BOMB and Chainlink for BTCB)
