### ISSUE TITLE
Create oracle wrapper for Flux

### ISSUE THREAD

**Issue by rhlsthrm** [Midas-Protocol/contracts#165]
## Background

Flux is live on Evmos testnet and supports a lot of the assets we need. We need to write a wrapper to support this.

### Linked Issues & Documentation

https://docs.fluxprotocol.org/docs/live-data-feeds/fpo-live-networks-and-pairs#devnet

## Definition Of Done

Oracle wrapper implementation created.

## Tasks

- [ ] Create oracle wrapper.
- [ ] Deploy to testnet.
- [ ] Test with pools.
