### ISSUE TITLE
GovernorBravo DAO

### ISSUE THREAD

**Issue by vminkov** [Midas-Protocol/contracts#236]
## Background

A DAO with the following characteristics has to be implemented:
- upgradeable - needs to keep balances/stakes over upgrades
- initially a DAO per chain
- multisig council has the final word on decisions (mechanism can be disabled/enabled)
- DAO voters vote to whitelist assets (and pools?)
- total chain rewards shares will be adjusted by the multisig council on a weekly basis
- partial voting should be possible to implement without much effort
- voting delegation is desirable if possible to implement without much effort

### Linked Issues & Documentation

- Midas-Protocol/contracts#240 
- Midas-Protocol/contracts#237 

## Definition Of Done

Forge tests (local or bsc testnet) are needed to verify that the enumerated features/mechanisms work.

## Tasks

- [ ] Implement (de)listing of markets by the owner and fuse admin.
- [ ] Change the (de)listing so only a single admin is able to (de)list.
- [ ] Implement test cases in which the DAO is the (de)listing admin and voting changes the (de)listing status of an asset in a pool.
- [ ] // TODO more tasks
- [ ] Booster for 30/70 split
