### ISSUE TITLE
Token implementation

### ISSUE THREAD

**Issue by vminkov** [Midas-Protocol/contracts#237]
## Background

- ERC20 - name to be decided later
- Use Solmate ERC20 with `permit` 

- Implement on the side linear time lock - use the Fei implementation https://github.com/fei-protocol/fei-protocol-core/blob/develop/contracts/timelocks/LinearTokenTimelock.sol
- Clawback / revoke
- Extra data arg for `transfer()` to enable direct deposits to CEX cold-wallets

### Linked Issues & Documentation

- Midas-Protocol/contracts#241 

## Definition Of Done

The token and timelock contracts are implemented and the `permit` function is tested in a unit test. The extra param on the `transfer` function is emitted with an addtional `Transfer()` event.
The deployment scripts are updated to include the token.

## Tasks

- [x] Implement ERC20 token
- [x] Implement timelocks for vesting
- [x] Unit test
- [x] Deployment script updated
