### ISSUE TITLE
Initial Chain Deployment: Neon

### ISSUE THREAD

**Issue by NikMidas** [Midas-Protocol/contracts#262]
## Chain Information

https://neon-labs.org

Link to Chain Developer docs: (https://docs.neon-labs.org/)

Native Wallet: *XXX*

**Mainnet**
Chain Name: NEON (Solana EVM)
Chain ID: *XXX*
RPC URL:  *XXX*
ChainExplorer: *XXX*
Native Token: *explorer url/XXX* <br>
Wrapped Native Token: *explorer url/XXX* <br>

**Testnet**
Chain Name: *XXX* <br>
Chain ID:  *XXX* <br>
RPC URL:  *XXX* <br>
Native Token: *explorer url/XXX* <br>
Wrapped Native Token: *explorer url/XXX* <br>

**Ecosystem**
Uniswap-clone project name: XXX <br>
Uniswap-clone docs: XXX <br>

## Tasks
*Please mark the tasks below, as appropriate.  Then link supporting Github items together using:* ![Screenshot of Github Link Button](https://user-images.githubusercontent.com/103433798/169572470-b7e31053-afab-4225-9816-6403193b86b3.png)

- [ ] Please use the link below to add initial set of assets <br>
   - [Link to Custom Asset Template](https://github.com/Midas-Protocol/monorepo/issues/new?assignees=&labels=Custom+Asset+Support&template=custom-asset-support.md&title=Support+Asset+%24XXX)
- [X] Create chain-specific deploy script inside `chainDeploy`
- [ ] Add the supported chain and its parameters to the [network configs](https://github.com/Midas-Protocol/contracts/blob/main/src/network.ts) of the SDK 
   - [ ] Blocks per year
   - [ ] Chain-specific addresses
   - [ ] Supported oracles
- [ ] Add network to hardhat config
- [ ] Run deploy script, export deployments and commit both `deployments.json` and deployments artifacts
- [ ] Redeploy SDK
- [ ] SDK
   - [ ] Add supported assets to `chainConfig/supportedAssets`
   - [ ] Add chain ids to `SupportedChains` enum
- [ ] UI
   - [ ] Add NEON Main and Testnet to `<SwitchNetworkModal/>`
   - [ ] Add `ChainMetadata` for Main & Testnet
   - [ ] Make sure Main & Testnet are Listed in `SupportedChains`
   - [ ] Deactivate Mainnet via `netlify.toml` until specific release
