### ISSUE TITLE
Whitelist for plugins used in CToken upgrades

### ISSUE THREAD

**Issue by vminkov** [Midas-Protocol/contracts#305]
## Background

In order to prevent the usage of custom, unchecked ERC4626 plugins in our markets (e.g. such that can be rug-pulled), we need to have a whitelist for plugins in the FuseFeeDistributor in a similar way to the existing whitelists for Comptroller and CErc20Delegate implementations.

### Linked Issues & Documentation

N/A

## Definition Of Done

The whitelists should work with the current autoimplementation flow with default address(0) value for the plugin address, so that the current plugin is not changed.

## Acceptance Criteria

Tests implemented and relevant deploy script changes done.

## Tasks

- [ ] Implement the plugins whitelist
- [ ] Make the upgrading of CErc20Delegate tokens compatible
- [ ] Make sure the autoimplementation mechanics work
