### ISSUE TITLE
Refactor oracles into chain-specific folders 

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/contracts#40]
## Background

We likely won't need all the oracles that are defined in the repo. We probably should refactor them into chain specific folders for ease of navigation.

Some oracle contracts would be cross chain. Decide which ones are like that.

### Linked Issues & Documentation

NA

## Definition Of Done

Oracles are refactored into their folders for chain-specific ones, whereas chain-agnostic oracles that require only some constructor args/custom initialisation are at the top level

## Tasks

- [ ] Move chain specific oracles into specific folders
- [ ] Decide which oracles we'll definitely need for each chain
- [ ] Determine which oracles can be used cross-chain
