### ISSUE TITLE
Forge-based Smart Contract tests 

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/contracts#51]
## Background

To test specific contracts, set up forge https://onbjerg.github.io/foundry-book/forge/index.html  framework. Research is required to ensure this works with our current hardhat-based configurations

### Linked Issues & Documentation

NA

## Definition Of Done

Automated test runs with forge 

## Tasks

- [ ] Research forge framework
- [ ] Implement basic tests
- [ ] Integrate into our repo, with tests for new 4626 plugins
