### ISSUE TITLE
Test liquidation via smart contract call

### ISSUE THREAD

**Issue by carlomazzaferro** [Midas-Protocol/contracts#8]
## Background

Test for smart contract call of `FuseSafeLiquidator` is needed to ensure liquidation of unhealthy pools can be performed programmatically. This is separate from our liquidation bots, which would monitor pool, and call the correct methods to liquidate them were they to fall below they health factor

### Linked Issues & Documentation

NA

## Definition Of Done

Liquidation is performed on an unhealthy pool 

## Tasks

- [ ] Create pool with assets 
- [ ] Post to a locally deployed price oracle a price that would result in liquidation
- [ ] Call liquidation contract function to perform liquidation
